/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 60f4a8bbb626f40e0f14c7c43b971c39)
interface __BaseEnv_Env {
	RECEIPTS: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "production" | "local";
	DOCUMENT_MAX_BYTES: "10485760";
	DEV_AUTH_ENABLED?: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface ProductionEnv {
		RECEIPTS: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "production";
		DOCUMENT_MAX_BYTES: "10485760";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DOCUMENT_MAX_BYTES" | "DEV_AUTH_ENABLED">> {}
}
