/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 78b54e820a877fee7fb37404a0f8e85c)
interface __BaseEnv_Env {
	RECEIPTS: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "production" | "local";
	DEV_AUTH_ENABLED?: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface ProductionEnv {
		RECEIPTS: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEV_AUTH_ENABLED">> {}
}
