import { Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import type { ExpenseCategory, ExpenseFilters as FilterValues, Person } from "./types";

type ExpenseFiltersProps = { categories: ExpenseCategory[]; filters: FilterValues; onChange: (next: Partial<FilterValues>) => void; people: Person[] };

export function ExpenseFilters({ categories, filters, onChange, people }: ExpenseFiltersProps) {
  const [expanded, setExpanded] = useState(Boolean(filters.categoryId || filters.paidByPersonId || filters.dateFrom || filters.dateTo));
  return <section className="expense-filters" aria-label="Expense filters"><div className="expense-filters__search"><Search aria-hidden="true" size={17} /><input aria-label="Search expenses" defaultValue={filters.search ?? ""} onChange={(event) => onChange({ search: event.target.value || undefined, page: 1 })} placeholder="Search expense, supplier, category" /></div><button aria-expanded={expanded} className="expense-filters__toggle" onClick={() => setExpanded((value) => !value)} type="button"><SlidersHorizontal aria-hidden="true" size={16} /> Filters</button>{expanded ? <div className="expense-filters__more"><label>Category<select aria-label="Filter by category" onChange={(event) => onChange({ categoryId: event.target.value || undefined, page: 1 })} value={filters.categoryId ?? ""}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Paid by<select aria-label="Filter by payer" onChange={(event) => onChange({ paidByPersonId: event.target.value || undefined, page: 1 })} value={filters.paidByPersonId ?? ""}><option value="">Everyone</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>From<input aria-label="From date" onChange={(event) => onChange({ dateFrom: event.target.value || undefined, page: 1 })} type="date" value={filters.dateFrom ?? ""} /></label><label>To<input aria-label="To date" onChange={(event) => onChange({ dateTo: event.target.value || undefined, page: 1 })} type="date" value={filters.dateTo ?? ""} /></label></div> : null}</section>;
}
